# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PQlt1eN8MRYGApjJ-fQ8tbkDXJi4sOsY
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/Dataset1.csv')
print(df.shape)

import pandas as pd
df = pd.read_csv('Dataset1.csv')
print(df.shape)
print(df.head())

print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])
print("\nColumn Names:")
print(df.columns.tolist())
print("\nData Types:")
print(df.dtypes)

routes = df.sort_values(['Train_No','SN']).groupby('Train_No').agg(
    Start_Station=('Station_Name','first'),
    End_Station=('Station_Name','last')
).reset_index()

print(routes.head(15))

# Task 1.2 - Train-wise Start & End Stations
print("\n" + "=" * 50)
print("TASK 1.2 - TRAIN-WISE ROUTES")
print("=" * 50)
routes = df.sort_values(['Train_No','SN']).groupby('Train_No').agg(
    Start_Station=('Station_Name','first'),
    End_Station=('Station_Name','last')
).reset_index()
print(routes.head(15))

print("\n" + "=" * 50)
print("TASK 1.3 - DISTANCE & STOPS STATISTICS")
print("=" * 50)
print("Distance Stats (km):\n", df['Distance'].describe().round(2))
stops_per_train = df.groupby('Train_No')['SN'].count()
print("\nNumber of Stops Stats:\n", stops_per_train.describe().round(2))

print("\n" + "=" * 50)
print("TASK 1.4 - MISSING & INCONSISTENT VALUES")
print("=" * 50)
print("Null Values:\n", df.isnull().sum())
print("\nDuplicate Rows:", df.duplicated().sum())
print("\nRows where Arrival = 00:00:00 (sentinel):", (df['Arrival_time'] == '00:00:00').sum())
print("Rows where Departure = 00:00:00 (sentinel):", (df['Departure_Time'] == '00:00:00').sum())

# Task 2.1 - Duplicates Remove karo
print("=" * 50)
print("TASK 2.1 - REMOVE DUPLICATES")
print("=" * 50)
df.drop_duplicates(inplace=True)
print("Duplicates removed. Remaining rows:", len(df))

# Task 2.2 - Time ko Minutes mein Convert karo
print("\n" + "=" * 50)
print("TASK 2.2 - STANDARDIZE TIME FORMAT")
print("=" * 50)
import numpy as np

def parse_time(t):
    try:
        h, m, s = map(int, t.strip().split(':'))
        total = h * 60 + m + s / 60
        return np.nan if total == 0 else total
    except:
        return np.nan

df['Arrival_min']   = df['Arrival_time'].apply(parse_time)
df['Departure_min'] = df['Departure_Time'].apply(parse_time)
print("Time columns converted to minutes!")
print(df[['Train_No','Station_Name','Arrival_min','Departure_min']].head(8))

# Task 2.3 - Journey Duration Calculate karo
print("\n" + "=" * 50)
print("TASK 2.3 - JOURNEY DURATION PER TRAIN")
print("=" * 50)

def compute_duration(group):
    dep_rows = group[group['Departure_min'].notna()]
    arr_rows = group[group['Arrival_min'].notna()]
    if dep_rows.empty or arr_rows.empty:
        return np.nan
    dep = dep_rows['Departure_min'].iloc[0]
    arr = arr_rows['Arrival_min'].iloc[-1]
    duration = arr - dep
    if duration < 0:
        duration += 24 * 60  # Overnight train correction
    return duration

train_duration = df.sort_values(['Train_No','SN']).groupby('Train_No').apply(compute_duration)
train_duration = train_duration.rename('Journey_Duration_min').reset_index()
print("Journey Duration Stats (minutes):\n", train_duration['Journey_Duration_min'].describe().round(2))

# Task 2.4 - Feature Table Banao
print("\n" + "=" * 50)
print("TASK 2.4 - CREATE FEATURE DATASET")
print("=" * 50)

dist_per_train  = df.groupby('Train_No')['Distance'].max().rename('Total_Distance_km').reset_index()
stops_per_train = df.groupby('Train_No')['SN'].count().rename('Num_Stops').reset_index()

feature_df = routes.merge(dist_per_train, on='Train_No')
feature_df = feature_df.merge(stops_per_train, on='Train_No')
feature_df = feature_df.merge(train_duration, on='Train_No')
feature_df = feature_df[(feature_df['Journey_Duration_min'] > 0) & (feature_df['Journey_Duration_min'] < 5000)]
feature_df['Journey_Duration_hr'] = (feature_df['Journey_Duration_min'] / 60).round(2)

print("Feature Dataset Shape:", feature_df.shape)
print(feature_df[['Train_No','Start_Station','End_Station',
                   'Total_Distance_km','Num_Stops','Journey_Duration_hr']].head(10))

print("\n✅ LEVEL 2 COMPLETE!")

# Task 3.1 - Journey Duration Compare karo
print("Average Duration:", feature_df['Journey_Duration_hr'].mean().round(2), "hrs")
print("Longest Journey :", feature_df['Journey_Duration_hr'].max(), "hrs")
print("Shortest Journey:", feature_df['Journey_Duration_hr'].min(), "hrs")

top5 = feature_df.nlargest(5, 'Journey_Duration_hr')[['Train_No','Start_Station','End_Station','Journey_Duration_hr']]
print("\nTop 5 Longest Journeys:\n", top5)

# Task 3.2 - Station Traffic
station_traffic = df.groupby('Station_Name').size().sort_values(ascending=False)
print("\nTop 10 Busiest Stations:\n", station_traffic.head(10))
print("\nTop 10 Least Busy Stations:\n", station_traffic.tail(10))

# Task 3.3 - Distance vs Duration Correlation
corr = feature_df[['Total_Distance_km','Num_Stops','Journey_Duration_min']].corr()
print("\nCorrelation Matrix:\n", corr.round(3))

import matplotlib.pyplot as plt
import seaborn as sns

# Task 4.1 - Journey Duration Distribution
plt.figure(figsize=(10,4))
plt.hist(feature_df['Journey_Duration_hr'], bins=50, color='steelblue', edgecolor='white')
plt.title("Journey Duration Distribution")
plt.xlabel("Duration (hours)")
plt.ylabel("Number of Trains")
plt.show()

# Task 4.2 - Top 15 Busiest Stations
top_stations = station_traffic.head(15).reset_index()
top_stations.columns = ['Station_Name', 'Train_Count']

plt.figure(figsize=(10,6))
sns.barplot(data=top_stations, x='Train_Count', y='Station_Name', hue='Station_Name', legend=False, palette='Blues_d')
plt.title("Top 15 Busiest Stations")
plt.xlabel("Number of Trains")
plt.ylabel("Station")
plt.show()

# Task 4.3 - Distance vs Journey Duration
plt.figure(figsize=(8,5))
plt.scatter(feature_df['Total_Distance_km'], feature_df['Journey_Duration_hr'], alpha=0.3, s=10, color='steelblue')
plt.title("Distance vs Journey Duration")
plt.xlabel("Distance (km)")
plt.ylabel("Duration (hrs)")
plt.show()

# Task 4.4 - Correlation Heatmap
plt.figure(figsize=(6,4))
corr_data = feature_df[['Total_Distance_km','Num_Stops','Journey_Duration_hr']].corr()
sns.heatmap(corr_data, annot=True, fmt='.2f', cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Task 5.1 - Modeling Dataset
model_df = feature_df[['Total_Distance_km','Num_Stops','Journey_Duration_min']].dropna()
model_df = model_df[model_df['Journey_Duration_min'] > 0]

X = model_df[['Total_Distance_km','Num_Stops']]
y = model_df['Journey_Duration_min']

# Task 5.2 - Train/Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Training samples:", len(X_train))
print("Testing samples :", len(X_test))

# Task 5.3 - Linear Regression Model
model = LinearRegression()
model.fit(X_train, y_train)
print("\nModel Trained!")
print("Intercept  :", round(model.intercept_, 2))
print("Coeff Distance:", round(model.coef_[0], 4), "mins per km")
print("Coeff Stops   :", round(model.coef_[1], 4), "mins per stop")

# Task 5.4 - Model Evaluation
y_pred = model.predict(X_test)
mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = model.score(X_test, y_test)

print("\nModel Performance:")
print("MAE  :", round(mae, 2), "minutes")
print("RMSE :", round(rmse, 2), "minutes")
print("R²   :", round(r2, 4))

